### ISSUE TITLE
Unable to add new esim (5ber esim)

### ISSUE THREAD

**Issue by ahmadnaim93** [tryigit/EsimEnable#4]
Model : Xiaomi 14
Rom : Xiaomi EU Stable 1.0.47.0

Unable to add new esim.
![screenshot](https://github.com/user-attachments/assets/57f871a1-0fec-4239-83ed-7739a71b623a)

I can add the profile through 5ber app and openeuicc (Xiaomi Mi 9, EvoX) without issue.

**Comment by tryigit** [comment]
Custom roms are not accepted.
